## Data cleaning and Preprocessing

In [1]:
# adding necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
# opening the dataset
data_filepath = "train_data/group_01_train.csv"
data = pd.read_csv(data_filepath)
data

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f26,f27,f28,f29,f30,f31,f32,f33,f34,y
0,Source2,2019-02-27 16:33:43,25.885487,-80.209206,NaN,0.000,Lane blocked due to accident on I-95 Northboun...,I-95 S,Miami-Dade,FL,...,False,False,False,False,False,Day,Day,Day,Day,3
1,Source2,2019-07-16 14:48:06,33.652409,-112.093979,NaN,0.000,Accident on Bluefield Ave at 16th Ave.,N 16th Ave,Maricopa,AZ,...,False,False,False,False,False,Day,Day,Day,Day,2
2,Source1,2022-06-11 21:38:22,40.725697,-73.899985,-73.886415,0.728,Incident on I-495 EB near GRAND AVE Expect lon...,Long Island Expy E,Queens,NY,...,False,False,False,False,False,Day,Day,Day,Day,2
3,Source1,2020-06-15 17:49:03,26.717860,-80.090410,-80.090410,0.000,At I-95 - Accident.,Palm Beach Lakes Blvd,Palm Beach,FL,...,False,False,False,False,False,Day,Day,Day,Day,2
4,Source2,2019-03-14 05:20:13,35.097069,-81.667786,NaN,0.000,Accident on I-85 Southbound after Exit 92 SC-11.,I-85 S,Cherokee,SC,...,False,False,False,False,False,Night,Night,Night,Night,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Source1,2021-06-08 11:16:30,39.748838,-78.182017,-78.184897,1.826,Stationary traffic on I-70 E - US-522 S from U...,Pigeon Cove Rd,Fulton,PA,...,False,False,False,False,False,Day,Day,Day,Day,2
99996,Source1,2021-11-27 11:38:11,38.677148,-120.918362,-120.945269,1.824,Accident on Shingle Springs Dr (US-50) from Ca...,El Dorado Fwy W,El Dorado,CA,...,False,False,False,False,False,Day,Day,Day,Day,2
99997,Source2,2019-08-01 06:05:23,32.895851,-96.899300,NaN,0.000,Accident on Royal Ln at Emerald St.,Emerald St,Dallas,TX,...,False,False,False,False,False,Night,Night,Night,Day,2
99998,Source1,2021-11-11 23:09:47,28.460345,-81.311589,-81.312289,0.058,Incident on NORTH FRONTAGE RD near FORBES PL R...,N Frontage Rd,Orange,FL,...,False,False,False,False,False,Night,Night,Night,Night,4
99999,Source1,2018-11-10 18:37:52,38.296387,-77.498571,-77.500052,0.081,At I-95/US-17 - Accident. Three lanes blocked.,Plank Rd,Fredericksburg,VA,...,False,False,False,False,False,Night,Night,Night,Day,3

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   f1      100000 non-null  object
 1   f2      100000 non-null  object
 2   f3      100000 non-null  float64
 3   f4      100000 non-null  float64
 4   f5      55938 non-null   float64
 5   f6      100000 non-null  float64
 6   f7      100000 non-null  object
 7   f8      99865 non-null   object
 8   f9      100000 non-null  object
 9   f10     100000 non-null  object
 10  f11     100000 non-null  object
 11  f12     99898 non-null   object
 12  f13     98483 non-null   object
 13  f14     74251 non-null   float64
 14  f15     97752 non-null   float64
 15  f16     98233 non-null   float64
 16  f17     97742 non-null   float64
 17  f18     97780 non-null   object
 18  f19     92639 non-null   float64
 19  f20     71752 non-null   float64
 20  f21     97760 non-null   object
 21  f22     100000 non-null  bool
 22  f23     100000 non-null  bool
 23  f24     100000 non-null  bool
 24  f25     100000 non-null  bool
 25  f26     100000 non-null  bool
 26  f27     100000 non-null  bool
 27  f28     100000 non-null  bool
 28  f29     100000 non-null  bool
 29  f30     100000 non-null  bool
 30  f31     99671 non-null   object
 31  f32     99671 non-null   object
 32  f33     99671 non-null   object
 33  f34     99671 non-null   object
 34  y       100000 non-null  int64
dtypes: bool(9), float64(10), int64(1), object(15)
memory usage: 20.7+ MB

In [4]:
# number of duplicated rows 
data.duplicated().sum()

np.int64(19)

In [5]:
# delete duplicated rows
data = data.drop_duplicates()

In [6]:
# here we look at what percentage of the columns are null
missing_values = data.isna().sum().sort_values(ascending=False)
missing_percentage = missing_values[missing_values!=0]/len(data)*100
missing_percentage

f5     44.068373
f20    28.251368
f14    25.751893
f19     7.361399
f17     2.258429
f15     2.248427
f21     2.240426
f18     2.220422
f16     1.767336
f13     1.517288
f31     0.329063
f33     0.329063
f32     0.329063
f34     0.329063
f8      0.135026
f12     0.102019
dtype: float64

In [7]:
# dropping columns with missing percentage of more than 20%
over_miss_cols = missing_percentage[missing_percentage > 20].index
data = data.drop(columns=over_miss_cols)
print("Dropped columns:")
print(list(over_miss_cols))

Dropped columns:
['f5', 'f20', 'f14']

In [8]:
pd.DataFrame({
    'Dtype': data.dtypes,
    'Missing Count': data.isna().sum()
}).query('`Missing Count` > 0').sort_values('Missing Count', ascending=False)

       Dtype  Missing Count
f19  float64           7360
f17  float64           2258
f15  float64           2248
f21   object           2240
f18   object           2220
f16  float64           1767
f13   object           1517
f31   object            329
f32   object            329
f33   object            329
f34   object            329
f8    object            135
f12   object            102

In [9]:
# filling numeric columns with the mean of their columns
numeric_cols = data.select_dtypes(include='number').columns
data[numeric_cols] = data[numeric_cols].fillna(data[numeric_cols].mean())

In [10]:
pd.DataFrame({
    'Dtype': data.dtypes,
    'Missing Count': data.isna().sum()
}).query('`Missing Count` > 0').sort_values('Missing Count', ascending=False)

      Dtype  Missing Count
f21  object           2240
f18  object           2220
f13  object           1517
f33  object            329
f31  object            329
f34  object            329
f32  object            329
f8   object            135
f12  object            102

In [11]:
# checking how many rows will be removed if we drop rows with missing values 
data1 = data
before = len(data1)
data1 = data1.dropna()
after = len(data1)

print("Rows removed:", before - after)

Rows removed: 3183

In [12]:
# only about 3% of the rows drop, its better to just drop them
data = data.dropna()

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96798 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   f1      96798 non-null  object
 1   f2      96798 non-null  object
 2   f3      96798 non-null  float64
 3   f4      96798 non-null  float64
 4   f6      96798 non-null  float64
 5   f7      96798 non-null  object
 6   f8      96798 non-null  object
 7   f9      96798 non-null  object
 8   f10     96798 non-null  object
 9   f11     96798 non-null  object
 10  f12     96798 non-null  object
 11  f13     96798 non-null  object
 12  f15     96798 non-null  float64
 13  f16     96798 non-null  float64
 14  f17     96798 non-null  float64
 15  f18     96798 non-null  object
 16  f19     96798 non-null  float64
 17  f21     96798 non-null  object
 18  f22     96798 non-null  bool
 19  f23     96798 non-null  bool
 20  f24     96798 non-null  bool
 21  f25     96798 non-null  bool
 22  f26     96798 non-null  bool
 23  f27     96798 non-null  bool
 24  f28     96798 non-null  bool
 25  f29     96798 non-null  bool
 26  f30     96798 non-null  bool
 27  f31     96798 non-null  object
 28  f32     96798 non-null  object
 29  f33     96798 non-null  object
 30  f34     96798 non-null  object
 31  y       96798 non-null  int64
dtypes: bool(9), float64(7), int64(1), object(15)
memory usage: 18.6+ MB

In [14]:
data.nunique()

f1         3
f2     96585
f3     87740
f4     87789
f6      6035
f7     89583
f8     31642
f9      1256
f10       49
f11        1
f12        4
f13    76627
f15      100
f16      855
f17       49
f18       24
f19       75
f21       81
f22        2
f23        2
f24        2
f25        2
f26        2
f27        2
f28        2
f29        2
f30        2
f31        2
f32        2
f33        2
f34        2
y          4
dtype: int64

In [15]:
# dropping f11 because the only value used in this column is is 'US'
data = data.drop(columns=['f11'])

In [16]:
# dropping f7 because converting it to a numerical value would need LLMs and NLPs which are not discussed in this course
data = data.drop(columns=['f7'])

In [17]:
# dropping f8 because of the same reason for the above cell
data = data.drop(columns=['f8'])

In [18]:
data.nunique()

f1         3
f2     96585
f3     87740
f4     87789
f6      6035
f9      1256
f10       49
f12        4
f13    76627
f15      100
f16      855
f17       49
f18       24
f19       75
f21       81
f22        2
f23        2
f24        2
f25        2
f26        2
f27        2
f28        2
f29        2
f30        2
f31        2
f32        2
f33        2
f34        2
y          4
dtype: int64

In [19]:
# converting the dates into the number of minutes passed from 00:00 24Hr format
dt = pd.to_datetime(
    data['f2'],
    format='ISO8601'
)

data['f2'] = (dt.dt.hour * 60 + dt.dt.minute).astype('int64')

In [20]:
# for other date column(f13), as we said in section1 it only represents the time of the report
# instead we replace values of the column with the season category
dt = pd.to_datetime(data['f13'], format='ISO8601')

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

data['f13'] = dt.dt.month.apply(get_season)

In [21]:
# f31 to f34 into boolean.
cols = ['f31', 'f32', 'f33', 'f34']

for col in cols:
    data[col] = data[col].map({
        'Day': False,
        'Night': True
    })

In [22]:
# frequency encoding for high cardinal columns
cols = ['f9', 'f10', 'f18', 'f21']

for col in cols:
    freq = data[col].value_counts()
    data[col] = data[col].map(freq)

In [23]:
# ont-hot-oncoding for categorical dtypes
cols = ['f1', 'f12', 'f13']

data = pd.get_dummies(
    data,
    columns=cols,
    dtype='int64'
)

In [24]:
data

,f2,f3,f4,f6,f9,f10,f15,f16,f17,f18,...,f1_Source2,f1_Source3,f12_US/Central,f12_US/Eastern,f12_US/Mountain,f12_US/Pacific,f13_Autumn,f13_Spring,f13_Summer,f13_Winter
0,993,25.885487,-80.209206,0.000,3249,11128,65.0,30.04,10.0,2240,...,1,0,0,1,0,0,0,0,0,1
2,1298,40.725697,-73.899985,0.728,544,4401,53.0,29.89,10.0,4908,...,0,0,0,1,0,0,0,0,1,0
3,1069,26.717860,-80.090410,0.000,396,11128,66.0,29.98,10.0,3341,...,0,0,0,1,0,0,0,0,1,0
4,320,35.097069,-81.667786,0.000,114,4812,76.0,30.23,10.0,4750,...,1,0,0,1,0,0,0,1,0,0
5,900,36.125492,-86.846878,0.000,1225,2126,39.0,30.35,10.0,3345,...,1,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,676,39.748838,-78.182017,1.826,669,3767,69.0,29.36,10.0,4499,...,0,0,0,1,0,0,0,0,1,0
99996,698,38.677148,-120.918362,1.824,141,21913,47.0,27.48,10.0,12636,...,0,0,0,0,0,1,1,0,0,0
99997,365,32.895851,-96.899300,0.000,1994,7310,72.0,29.49,10.0,4400,...,1,0,1,0,0,0,0,0,1,0
99998,1389,28.460345,-81.311589,0.058,3122,11128,96.0,29.96,10.0,5394,...,0,0,0,1,0,0,1,0,0,0
99999,1117,38.296387,-77.498571,0.081,16,3694,44.0,30.29,10.0,4131,...,0,0,0,1,0,0,1,0,0,0

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96798 entries, 0 to 99999
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   f2               96798 non-null  int64
 1   f3               96798 non-null  float64
 2   f4               96798 non-null  float64
 3   f6               96798 non-null  float64
 4   f9               96798 non-null  int64
 5   f10              96798 non-null  int64
 6   f15              96798 non-null  float64
 7   f16              96798 non-null  float64
 8   f17              96798 non-null  float64
 9   f18              96798 non-null  int64
 10  f19              96798 non-null  float64
 11  f21              96798 non-null  int64
 12  f22              96798 non-null  bool
 13  f23              96798 non-null  bool
 14  f24              96798 non-null  bool
 15  f25              96798 non-null  bool
 16  f26              96798 non-null  bool
 17  f27              96798 non-null  bool
 18  f28              96798 non-null  bool
 19  f29              96798 non-null  bool
 20  f30              96798 non-null  bool
 21  f31              96798 non-null  bool
 22  f32              96798 non-null  bool
 23  f33              96798 non-null  bool
 24  f34              96798 non-null  bool
 25  y                96798 non-null  int64
 26  f1_Source1       96798 non-null  int64
 27  f1_Source2       96798 non-null  int64
 28  f1_Source3       96798 non-null  int64
 29  f12_US/Central   96798 non-null  int64
 30  f12_US/Eastern   96798 non-null  int64
 31  f12_US/Mountain  96798 non-null  int64
 32  f12_US/Pacific   96798 non-null  int64
 33  f13_Autumn       96798 non-null  int64
 34  f13_Spring       96798 non-null  int64
 35  f13_Summer       96798 non-null  int64
 36  f13_Winter       96798 non-null  int64
dtypes: bool(13), float64(7), int64(17)
memory usage: 19.7 MB

In [26]:
# columns standardization
num_cols = [
    col for col in data.select_dtypes(include='number').columns
    if col != 'y'
]

scaler = StandardScaler()

data[num_cols] = scaler.fit_transform(data[num_cols])
data[num_cols] = data[num_cols].round(2)

In [27]:
# number of duplicate rows
data.duplicated().sum()

np.int64(25)

In [28]:
# getting rid of duplicate rows
data = data.drop_duplicates()

In [30]:
data.to_csv('train_data/preprocessed_train.csv', index=False)